<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HTCLT1474" failures="5" tests="12" name="Opportunity" time="160.42" errors="0" timestamp="2023-12-01T16:58:18 IST">
  <testcase classname="Test.Opportunity_Scenario" name="Login_Salesforce_page" time="6.649"/>
  <testcase classname="Test.Opportunity_Scenario" name="Homepage" time="7.532"/>
  <testcase classname="Test.Opportunity_Scenario" name="Opportunity_Layouts" time="18.097"/>
  <testcase classname="Test.Opportunity_Scenario" name="Opportunity_Date_Field_Type" time="7.168"/>
  <testcase classname="Test.Opportunity_Scenario" name="AutopopulateAnnualRevenue" time="12.638"/>
  <testcase classname="Test.Opportunity_Scenario" name="Qualification_NewTask" time="18.774"/>
  <testcase classname="Test.Opportunity_Scenario" name="AutoPopulate_Contact" time="10.568">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Opportunity_Scenario.AutoPopulate_Contact(Opportunity_Scenario.java:188)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- AutoPopulate_Contact -->
  <testcase classname="Test.Opportunity_Scenario" name="Quote_created_tab" time="15.802">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Opportunity_Scenario.Quote_created_tab(Opportunity_Scenario.java:207)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Quote_created_tab -->
  <testcase classname="Test.Opportunity_Scenario" name="Quote_created_PDF" time="5.056">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Opportunity_Scenario.Quote_created_PDF(Opportunity_Scenario.java:225)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Quote_created_PDF -->
  <testcase classname="Test.Opportunity_Scenario" name="Closed_won" time="8.61">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Opportunity_Scenario.Closed_won(Opportunity_Scenario.java:244)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Closed_won -->
  <testcase classname="Test.Opportunity_Scenario" name="Contract_Created" time="28.604"/>
  <testcase classname="Test.Opportunity_Scenario" name="Contract_Lost" time="16.051">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Opportunity_Scenario.Contract_Lost(Opportunity_Scenario.java:281)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Contract_Lost -->
</testsuite> <!-- Opportunity -->
